### ISSUE TITLE
JRuby Certificate is invalid

### ISSUE THREAD

**Issue by astrieanna** [jruby/jruby.github.io#12]
The https connection to JRuby.org appears as insecure because the certificate is invalid.

![screen shot 2018-06-28 at 2 39 26 pm](https://user-images.githubusercontent.com/1205394/42054051-4f593bee-7ae1-11e8-80fb-5dd4f8d2d3e9.png)

It looks like it's using a cert for github.com, but the site is jruby.org.

**Comment by sfgeorge** [comment]
⏫ Agreed, this is important.

1. The https://jruby.github.io uses a valid cert for `*.gihub.io` 👍  But  https://jruby.org needs an SSL cert for jruby.org.
2. https://jruby.github.io redirects to http://jruby.org .  It should redirect to https://jruby.org (once 1. is fixed)
3. All http://jruby.org/ requests should redirect to https://jruby.org (once 1. is fixed)

**Comment by sfgeorge** [comment]
According to the GitHub Blog Post, [Custom domains on GitHub Pages gain support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain):

> If you are using CNAME or ALIAS records for your custom domain, you’re all set and your site should be accessible over HTTPS. 

jruby.org doesn't currently use MX records, in which case either of the above options are good.  But if we want to leave mail functionality open as a possibility, then I'd suggest against using CNAME.   

CNAME would break mail functionality for a domain.  [as suggested here on S.O.](https://webmasters.stackexchange.com/a/105971/89695), a good approach is to use A, ALIAS or ANAME - but not a CNAME.

[GitHub Help: Setting up an apex domain
](https://help.github.com/articles/setting-up-an-apex-domain/)

**Comment by headius** [comment]
Thanks for the tips, folks. We fixed this a couple months ago.

![image](https://user-images.githubusercontent.com/10135/49338178-56c0f600-f616-11e8-8e9b-730dec6053d9.png)
