### ISSUE TITLE
Provide sha256sums

### ISSUE THREAD

**Issue by envygeeks** [jruby/jruby.github.io#2]
Jekyll just started providing official JRuby support but we ran into a snag with our Docker images and our Deb's in that our build system requires Sha256sums to confirm a download, can you please start providing sha256sum's of your builds please?

**Comment by BanzaiMan** [comment]
I've created https://github.com/jruby/jruby/issues/3135 to replace this.

I don't think we should keep a separate issue tracker for the web site, so I'm going to disable it after this comment.
