### ISSUE TITLE
Bloggers to add to the /blogs page

### ISSUE THREAD

**Issue by olleolleolle** [jruby/jruby.github.io#9]
The /blogs page could perhaps be updated to reflect currently-outputting bloggers writing about JRuby.

Some of the current links on the page have not been updated in the past years. Should they be relegated to Alumni status?

Note: the TruffleRuby project is its own universe.

**Comment by headius** [comment]
The TruffleRuby folks are entirely separate from this project now, so I'm not sure they're really relevant to JRuby.

I need to start blogging again.

**Comment by olleolleolle** [comment]
Yeah, go blogging! I'll re-word the Description.
